In [2]:
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


###Simple multiplicatipon

In [4]:
revenue = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])

In [5]:
#  In the form of Indian rupees: 
revenue*75

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

###Total sales in every months

In [6]:
Units_sold = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])

In [7]:
Units_sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [8]:
price_per_unit = np.array([20, 30, 15])

In [9]:
price_per_unit

array([20, 30, 15])

In [10]:
total_sales = np.dot(price_per_unit, Units_sold)

In [11]:
total_sales

array([1900, 2640, 1430])

###Absolute and mean absolute error

In [14]:
y_predicted = np.array([1,1,0,0,1,0])
y_true = np.array([0.3,0.77,0.9,0.6, 0.5,0.99])

In [23]:
np.mean(np.abs(y_predicted - y_true))

0.6533333333333333

In [32]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

difference_array = np.array(array1 - array2)
squared_array = np.square(difference_array)
mse = squared_array.mean()

print(mse)

9.0


In [33]:
difference_array

array([-3, -3, -3])

In [34]:
A = np.array([[1,2,3,5], [3,4,5,6]])

In [35]:
np.square(A)

array([[ 1,  4,  9, 25],
       [ 9, 16, 25, 36]])