In [3]:
import numpy as np

###Simple multiplicatipon

In [4]:
revenue = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])

In [5]:
#  In the form of Indian rupees: 
revenue*75

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

###Total sales in every months

In [6]:
Units_sold = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])

In [7]:
Units_sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [8]:
price_per_unit = np.array([20, 30, 15])

In [9]:
price_per_unit

array([20, 30, 15])

In [10]:
total_sales = np.dot(price_per_unit, Units_sold)

In [11]:
total_sales

array([1900, 2640, 1430])

###Mean absolute error and mean squared error

In [12]:
y_predicted = np.array([1,1,0,0,1,0])
y_true = np.array([0.3,0.77,0.9,0.6, 0.5,0.99])

##Implementation

In [13]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [15]:
mae(y_predicted, y_true)

Total error is: 3.92
Mean absolute error is: 0.6533333333333333


0.6533333333333333

In [23]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [24]:
mse(y_true, y_predicted)

Total Squared Error: 2.9429999999999996
Mean Squared Error: 0.49049999999999994


0.49049999999999994

**another trick**

In [29]:
difference_array = np.array(y_true - y_predicted)
squared_array = np.square(difference_array)
mse = squared_array.mean()

print(mse)

0.49049999999999994


##Using numpy

In [18]:
np.mean(np.abs(y_predicted - y_true))

0.6533333333333333

In [26]:
np.mean(np.square(y_true-y_predicted))

0.49049999999999994

In [20]:
difference_array

array([-3, -3, -3])

In [21]:
A = np.array([[1,2,3,5], [3,4,5,6]])

In [22]:
np.square(A)

array([[ 1,  4,  9, 25],
       [ 9, 16, 25, 36]])

#Implement Log Loss or Binary Cross Entropy

In [30]:
np.log([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [31]:
epsilon = 1e-15

In [32]:
np.log([1e-15])


array([-34.53877639])

In [33]:
y_predicted

array([1, 1, 0, 0, 1, 0])

In [34]:

y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1, 1e-15]

In [35]:
1-epsilon

0.999999999999999

In [36]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999, 1e-15]

In [37]:
y_predicted_new = np.array(y_predicted_new)

In [38]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16, -3.45387764e+01])

In [39]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

22.56552448206251

In [40]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [41]:
log_loss(y_true, y_predicted)

22.56552448206251